defaults: &defaults
  auth_keys:
    facebook_id: '587450764608725'
    facebook_secret: '210bf438ba7749541f21401cbc70ab52'
    github_id: '73a3698de16e3be8c6d0'
    github_secret: 2a03ca8180e5655d48395304b15f8abe34b84d67
    google_id: '1001644837540.apps.googleusercontent.com'
    google_secret: 'Vhfdr24B3SJFFgKbt-3lmZCk'
production:
  auth_keys: 
    github_id: 'fe21a88d2a8468781dda'
    github_secret: '08dde0b58749a6fb08ea2fdbef898bb8595f5fac'
    google_id: ''
    google_secret: ''
    facebook_id: '659473207411610'
    facebook_secret: '5c114f3bd58657dbc9cf2a2faf75243b'
    
development:
  <<: *defaults
test: 
  <<: *defaults